---
name: Loki
url: https://github.com/mdegat01/addon-loki
version: edge
slug: loki
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
description: Loki for Home Assistant
startup: system
map:
  - share
  - ssl
watchdog: http://[HOST]:3101/ready
ports:
  3100/tcp:
ports_description:
  3100/tcp: HTTP listen port
options:
  ssl: false
  days_to_keep: 30
  log_level: info
schema:
  ssl: bool
  certfile: str?
  keyfile: str?
  cafile: str?
  days_to_keep: int(1,)?
  config_path: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
